name: Authentication

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/authentication.yml'
      - 'authentication/**'
      - 'scripts/*'
      - 'scripts/authentication.sh'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/authentication.yml'
      - 'authentication/**'
      - 'scripts/*'
      - 'scripts/authentication.sh'

  workflow_dispatch:

env:
  SAMPLE: Authentication
  secrets_passphrase: ${{ secrets.GHASECRETSGPGPASSPHRASE1 }}

jobs:
  cocoapods:
    name: cocoapods
    runs-on: macos-12
    strategy:
      matrix:
        xcode: ["13.3.1", "14.0"]
    env:
      SPM: false
      LEGACY: false
      OS: iOS
      DEVICE: iPhone 11
      TEST: false
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Xcode ${{ matrix.xcode }}
      - name: Setup
        run: |
          cd authentication
          gem install bundler
          bundle install
          gem install xcpretty
          bundle exec pod install --repo-update
          ../scripts/install_prereqs/authentication.sh
      - name: Build Swift
        run: ./scripts/test.sh
        env:
          SWIFT_SUFFIX: ""
