name: Remote Config

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/config.yml'
      - 'config/**'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/config.yml'
      - 'config/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: build
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup
        run: |
          cd config
          gem install bundler
          bundle install
          gem install xcpretty
          bundle exec pod install --repo-update
          ../scripts/install_prereqs/config.sh
        env:
          SAMPLE: Config
      - name: Build ObjC
        run: ./scripts/test.sh
        env:
          SWIFT_SUFFIX: ''
          SAMPLE: Config
      - name: Build Swift
        run: ./scripts/test.sh
        env:
          SWIFT_SUFFIX: 'Swift'
          SAMPLE: Config
