name: Config

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: build
    runs-on: macOS-latest
    strategy:
        matrix:
          swift-suffix: ['', 'Swift']

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: |
          cd config
          gem install bundler
          bundle install
          gem install xcpretty
          bundle exec pod install --repo-update
          ../scripts/install_prereqs/config.sh
          cd -
          ./scripts/test.sh
        env:
          SWIFT_SUFFIX: ${{ matrix.swift-suffix }}
          SAMPLE: Config
