name: Crashlytics

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/crashlytics.yml'
      - 'crashlytics/**'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/crashlytics.yml'
      - 'crashlytics/**'

  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup
        run: |
          cd crashlytics
          gem install bundler
          bundle install
          gem install xcpretty
          bundle exec pod install --repo-update
          ../scripts/install_prereqs/crashlytics.sh
        env:
          SAMPLE: Crashlytics
      - name: Build ObjC
        run:  ./scripts/test.sh
        env:
          SWIFT_SUFFIX: ''
          SAMPLE: Crashlytics
      - name: Build Swift
        run:  ./scripts/test.sh
        env:
          SWIFT_SUFFIX: 'Swift'
          SAMPLE: Crashlytics
