name: Database

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/database.yml'
      - 'database/**'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/database.yml'
      - 'database/**'

  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup
        run: |
          cd database
          gem install bundler
          bundle install
          gem install xcpretty
          bundle exec pod install --repo-update
          ../scripts/install_prereqs/database.sh
        env:
          SAMPLE: Database
      - name: Build ObjC
        run: ./scripts/test.sh
        env:
          SWIFT_SUFFIX: ''
          SAMPLE: Database
      - name: Build Swift
        run: ./scripts/test.sh
        env:
          SWIFT_SUFFIX: 'Swift'
          SAMPLE: Database
