name: DynamicLinks

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/dynamiclinks.yml'
      - 'dynamiclinks/**'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/dynamiclinks.yml'
      - 'dynamiclinks/**'

  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup
        run: |
          cd dynamiclinks
          gem install bundler
          bundle install
          gem install xcpretty
          bundle exec pod install --repo-update
          ../scripts/install_prereqs/dynamiclinks.sh
        env:
          SAMPLE: DynamicLinks
      - name: Build ObjC
        run: |
          ./scripts/test.sh
        env:
          SWIFT_SUFFIX: ''
          SAMPLE: DynamicLinks
      - name: Build Swift
        run: |
          ./scripts/test.sh
        env:
          SWIFT_SUFFIX: 'Swift'
          SAMPLE: DynamicLinks
